// Vendors
import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// Components
import { Header } from '@/components/Header';
import { StylesProvider } from '@/core/providers/StylesProvider';

// Styles
import { StyledLayout, StyledLayoutContent } from '@/app/styled';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StylesProvider>
          <StyledLayout>
            <Header />

            <StyledLayoutContent>{children}</StyledLayoutContent>
          </StyledLayout>
        </StylesProvider>
      </body>
    </html>
  );
}
